image: adoptopenjdk/openjdk13

stages:
  - build
  - test
  - deploy

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - apt-get update
  - apt-get -y install software-properties-common
  - apt-get update
  - apt-get -y install curl
  - curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose
  - docker-compose --version
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - add-apt-repository ppa:webupd8team/java
  - apt update
  - apt install oracle-java8-installer
  - JAVA8_HOME=/opt/java/1.8
  - PATH=/opt/java/1.8/bin:$PATH

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

# build:
#   stage: build
#   script:
#     - ./gradlew assemble --stacktrace --info
#     # - apt-get update
#     # - apt-get -y install wget
#     # - wget -q https://raw.githubusercontent.com/linux-on-ibm-z/scripts/master/Elasticsearch/7.4.1/build_elasticsearch.sh
#     # - bash build_elasticsearch.sh
#   artifacts:
#     paths:
#       - build/libs/*.jar
#     expire_in: 1 week
#   only:
#     - master

test:
  stage: test
  script:
    - ./gradlew check -Dbuild.docker=false

#deploy:
#  stage: deploy
#  script:
#    - ./deploy

after_script:
  - echo "End CI"
