version: '2.2'
services:
  elasticsearch:
    # Roule le dockerfile
    build: .
    
    # container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # volumes:
    #   - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - esnet    
  
# CATALINA_OPTS: '-agentpath:/usr/local/jprofiler10.0.4/bin/linux-x64/libjprofilerti.so=port=8849'
  # elasticsearch2:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.8.6
  #   container_name: elasticsearch2
  #   environment:
  #     - cluster.name=docker-cluster
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.zen.ping.unicast.hosts=elasticsearch"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata2:/usr/share/elasticsearch/data
  #   networks:
  #     - esnet

# volumes:
#   esdata1:
#     driver: local
  # esdata2:
  #   driver: local

networks:
  esnet: