name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with: 
        java-version: 13
    - name: Permission for gradlew
      run: chmod +x gradlew
    - name: Move to modules
      run: cd modules/
      
    - name: Test module aggs-matrix-stats
      run: gradle :modules:aggs-matrix-stats:test
    - name: Save module aggs-matrix-stats test reports
      uses: actions/upload-artifact@v1
      with:
        name: aggs-matrix-stats-test-reports
        path: modules/aggs-matrix-stats/build/reports/tests/test
    
    - name: Test module ingest-geoip
      run: gradle :modules:ingest-geoip:test
    - name: Save module ingest-geoip test reports
      uses: actions/upload-artifact@v1
      with:
        name: ingest-geoip-test-reports
        path: modules/ingest-geoip/build/reports/tests/test
        
        
    - name: Test module ingest-user-agent
      run: gradle :modules:ingest-user-agent:test
    - name: Save module ingest-user-agent test reports
      uses: actions/upload-artifact@v1
      with:
        name: ingest-user-agent-test-reports
        path: modules/ingest-user-agent/build/reports/tests/test
        
    - name: Test module repository-url
      run: gradle :modules:repository-url:test
    - name: Save module repository-url test reports
      uses: actions/upload-artifact@v1
      with:
        name: repository-url-test-reports
        path: modules/repository-url/build/reports/tests/test
